const links = {
  view: "https://reactnative.dev/docs/view",
  text: "https://reactnative.dev/docs/text",
  animatedView: "https://reactnative.dev/docs/animations#animated-api",
  pressable: "https://reactnative.dev/docs/pressable",
  textInput: "https://reactnative.dev/docs/textinput",
  modal: "https://reactnative.dev/docs/modal",
  expoIcons: "https://docs.expo.dev/guides/icons/#properties",
  github: "https://github.com/CFBSTexas/cfbsstrap-native",
};

const pageNames: { [key: string]: string } = {
  Home: "Home",
  Installation: "Installation",
  Responsive: "Responsive",
  Accordion: "Accordion",
  AccordionBody: "Accordion.Body",
  AccordionHeader: "Accordion.Header",
  AccordionItem: "Accordion.Item",
  AccordionTitle: "Accordion.Title",
  AccordionToggle: "Accordion.Toggle",
  Alert: "Alert",
  Animation: "Animation",
  AnimationFadeIn: "Animation.FadeIn",
  Button: "Button",
  Calendar: "Calendar",
  CalendarDays: "Calendar.Days",
  CalendarDay: "Calendar.Day",
  CalendarHeader: "Calendar.Header",
  CalendarLeft: "Calendar.Left",
  CalendarRight: "Calendar.Right",
  CalendarTitle: "Calendar.Title",
  CalendarWeekday: "Calendar.Weekday",
  CalendarWeekdays: "Calendar.Weekdays",
  CloseButton: "Button.Close",
  Card: "Card",
  CardBody: "Card.Body",
  CardHeader: "Card.Header",
  CardSubtitle: "Card.Subtitle",
  CardTitle: "Card.Title",
  Center: "Center",
  Col: "Col",
  Div: "Div",
  Drawer: "Drawer",
  DrawerBody: "Drawer.Body",
  DrawerHeader: "Drawer.Header",
  DrawerToggle: "Drawer.Toggle",
  Form: "Form",
  FormButton: "Form.Button",
  FormInput: "Form.Input",
  FormLabel: "Form.Label",
  Input: "Input",
  InputCheckbox: "Input.Checkbox",
  InputRadio: "Input.Radio",
  InputSearch: "Input.Search",
  InputSelect: "Input.Select",
  InputSwitch: "Input.Switch",
  InputDate: "Input.Date",
  InputText: "Input.Text",
  InputTextArea: "Input.TextArea",
  InputNumber: "Input.Number",
  Link: "Link",
  Modal: "Modal",
  ModalBody: "Modal.Body",
  ModalFooter: "Modal.Footer",
  ModalHeader: "Modal.Header",
  ModalTitle: "Modal.Title",
  Menu: "Menu",
  MenuItem: "Menu.Item",
  MenuToggle: "Menu.Toggle",
  Pagination: "Pagination",
  PaginationFirst: "Pagination.First",
  PaginationLast: "Pagination.Last",
  PaginationNext: "Pagination.Next",
  PaginationPrevious: "Pagination.Previous",
  PaginationItem: "Pagination.Item",
  Popup: "Popup",
  Progress: "Progress",
  ProgressBar: "Progress.Bar",
  ProgressSpinner: "Progress.Spinner",
  ProgressText: "Progress.Text",
  Row: "Row",
  Tab: "Tab",
  Table: "Table",
  TableTd: "Table.td",
  TableTh: "Table.th",
  TableTr: "Table.tr",
  Tabs: "Tabs",
  Text: "Text",
};

const packageName = "react-native-kit";

export { links, pageNames, packageName };
